---
title: "Divvy Case Study"
author: "Andrew Luyt"
date: "`r paste('<br>Last updated: ',format(Sys.Date(), '%A %B %d, %Y'))`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This case study explores a real-world public dataset from *Divvy*, a
bike-sharing company run cooperatively between the City of Chicago and
Motivate International Inc. The system provides bicycles in a city-wide
network of docking stations which can be accessed by annual members or
casual users who purchase a single-ride or day pass. Well over four
million rides have been taken on the system between June 2020 and July 2021.

This case study will explore the difference between members & casual
users, and patterns of overall system use, particularly traffic volume and flow.

# TODO: links to sections, highlights first, don't bury lede, use images.

- [Introduction](introduction.md)
- [Analysis](analysis-report.md)
- [Data Cleaning](process-bikeshare-data.md)

